steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker login --username=$$USERNAME --password=$$PASSWORD"]
    secretEnv: ["USERNAME", "PASSWORD"]
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker build . -t $_REPOSITORY:$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker push $_REPOSITORY:$SHORT_SHA"]

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ["-c", "sed -i 's+$_REPOSITORY.*+$_REPOSITORY:$SHORT_SHA+g' $_K8S_YAML_PATH"]

    #  - name: 'gcr.io/cloud-builders/gke-deploy'
    #    id: 'Apply deploy'
    #    args:
    #    - 'run'
    #    - '--filename=$_K8S_YAML_PATH'
    #    - '--namespace=$_K8S_NAMESPACE'
    #    - '--cluster=$_GKE_CLUSTER'
    #    - '--location=$_GKE_LOCATION'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DOCKERHUB_REGISTRY_PASSWORD/versions/1
      env: "PASSWORD"
    - versionName: projects/$PROJECT_ID/secrets/DOCKERHUB_REGISTRY_USER/versions/1
      env: "USERNAME"

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'

substitutions:
  _DOCKERFILE_PATH: Dockerfile
  _REPOSITORY: drtinkerer/maventest
  _GKE_CLUSTER: autopilot-cluster-1
  _GKE_LOCATION: asia-south1
  _K8S_YAML_PATH: deployment.yaml
  _K8S_APP_NAME: test
  _K8S_NAMESPACE: test
